export const pokeballClasses = [
    {
      id: "1",
      type: "Poke Ball",
      price: "200",
      backgroundPosition: "-10000px 0",
    },
    {
      id: "2",
      type: "Great Ball",
      price: "600",
      backgroundPosition: "212px 1px",
    },
    {
      id: "3",
      type: "Ultra Ball",
      price: "800",
      backgroundPosition: "285px 1px",
    },
    {
      id: "4",
      type: "Master Ball",
      price: "4000",
      backgroundPosition: "354px 1px",
    },
    {
      id: "5",
      type: "Safari Ball",
      price: "1000",
      backgroundPosition: "426px 1px",
    },
    {
      id: "6",
      type: "Level Ball",
      price: "1000",
      backgroundPosition: "1px 60px",
    },
    {
      id: "7",
      type: "Lure Ball",
      price: "2000",
      backgroundPosition: "-600px -1px",
    },
    {
      id: "8",
      type: "Friend Ball",
      price: "1000",
      backgroundPosition: "",
    },
    {
      id: "9",
      type: "Moon Ball",
      price: "2000",
      backgroundPosition: "",
    },
    {
      id: "10",
      type: "Love Ball",
      price: "2000",
      backgroundPosition: "",
    },
    {
      id: "11",
      type: "Fast Ball",
      price: "3000",
      backgroundPosition: "",
    },
    {
      id: "12",
      type: "Heavy Ball",
      price: "3000",
      backgroundPosition: "",
    },
    {
      id: "13",
      type: "Sports Ball",
      price: "1000",
      backgroundPosition: "",
    },
    {
      id: "14",
      type: "Park Ball",
      price: "1000",
      backgroundPosition: "",
    },
    {
      id: "15",
      type: "Premier Ball",
      price: "1000",
      backgroundPosition: "",
    },
    {
      id: "16",
      type: "Repeat Ball",
      price: "1000",
      backgroundPosition: "1",
    },
    {
      id: "17",
      type: "Timer Ball",
      price: "1000",
      backgroundPosition: "2",
    },
    {
      id: "18",
      type: "Nest Ball",
      price: "1000",
      backgroundPosition: "2",
    },
    {
      id: "19",
      type: "Net Ball",
      price: "1000",
      backgroundPosition: "3",
    },
    {
      id: "20",
      type: "Dive Ball",
      price: "1000",
      backgroundPosition: "4",
    },
    {
      id: "21",
      type: "Luxury Ball",
      price: "3000",
      backgroundPosition: "4",
    },
    {
      id: "22",
      type: "Heal Ball",
      price: "300",
      backgroundPosition: "1",
    },
    {
      id: "23",
      type: "Quick Ball",
      price: "1000",
      backgroundPosition: "2",
    },
    {
      id: "24",
      type: "Dusk Ball",
      price: "1000",
      backgroundPosition: "2",
    },
    {
      id: "25",
      type: "Cherish Ball",
      price: "1000",
      backgroundPosition: "3",
    },
    {
      id: "26",
      type: "Park Ball",
      price: "1000",
      backgroundPosition: "4",
    },
    {
      id: "27",
      type: "Dream Ball",
      price: "2000",
      backgroundPosition: "2",
    },
    {
      id: "28",
      type: "GS Ball",
      price: "2000",
      backgroundPosition: "1",
    },
  ];